version: '3'
services:
  hexagonal-architecture:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "80:8080"

  mongodb:
    image: 'mongo:4.4.6'
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb